routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade

  /project/beautiful-trip/:
    template: project
    data: page.beautiful-trip

collections:
  /:
    permalink: /post/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
