routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade

collections:
  /:
    permalink: /post/{slug}/
    template: index
  /projects/:
    permalink: /project/{slug}/
    template: project

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
